/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

import java.awt.Color;
import java.awt.event.KeyEvent;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Dankiwan
 */
public class Prescription extends javax.swing.JInternalFrame {

    private static Prescription prescriptioninstance;
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    int xxx, xxx2;
    String pid = null;
    String fname, lname, titlee;
    int day, month, year;
    String[] colnames = {"Code", "Name", "Drug Quantity", "Items", "Dosage", "Administration", "Frequency", "Description", " Cost", " Status"};
    DefaultTableModel model = new DefaultTableModel(colnames, 0);
    String[] icolnames = {"Name", "Description", "Date"};
    DefaultTableModel model1 = new DefaultTableModel(icolnames, 0);

    /**
     * Creates new form Prescription
     */
    public Prescription() {
        initComponents();
        con = javaconnect.ConnectDb();
        datenandtime();
        btn_inje_re.setEnabled(false);
        btn_r_m.setEnabled(false);
             ListSelectionModel listSelectionModel = table_med.getSelectionModel();
        listSelectionModel.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent lse) {
                ListSelectionModel lsm = (ListSelectionModel) lse.getSource();
                btn_r_m.setEnabled(!lsm.isSelectionEmpty());
            }
        });
               ListSelectionModel lisstSelectionModel = table_inje.getSelectionModel();
        lisstSelectionModel.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent lse) {
                ListSelectionModel lsm = (ListSelectionModel) lse.getSource();
                btn_inje_re.setEnabled(!lsm.isSelectionEmpty());
            }
        });

    }

    public Prescription PrescriptionInstance() {
        if (prescriptioninstance == null) {
            prescriptioninstance = new Prescription();
        }
        return prescriptioninstance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        txt_user = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jButton4 = new javax.swing.JButton();
        btn_r_m = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_med = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jToolBar3 = new javax.swing.JToolBar();
        jButton10 = new javax.swing.JButton();
        btn_inje_re = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_inje = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_dietadvice = new javax.swing.JTextPane();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton8 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton7 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();

        setClosable(true);

        jPanel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ENTER PATIENT ID.");

        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_searchKeyTyped(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-icon.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Diagonis Details"));

        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton5)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jToolBar2.setRollover(true);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon_1.png"))); // NOI18N
        jButton4.setText("Add Drug");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton4);

        btn_r_m.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del-icon.png"))); // NOI18N
        btn_r_m.setText("Remove");
        btn_r_m.setFocusable(false);
        btn_r_m.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_r_m.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_r_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_r_mActionPerformed(evt);
            }
        });
        jToolBar2.add(btn_r_m);

        table_med.setModel(model);
        jScrollPane2.setViewportView(table_med);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MEDICINE", jPanel5);

        jToolBar3.setRollover(true);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon_1.png"))); // NOI18N
        jButton10.setText("Add Injection");
        jButton10.setFocusable(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jToolBar3.add(jButton10);

        btn_inje_re.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/del-icon.png"))); // NOI18N
        btn_inje_re.setText("Remove");
        btn_inje_re.setFocusable(false);
        btn_inje_re.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_inje_re.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_inje_re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inje_reActionPerformed(evt);
            }
        });
        jToolBar3.add(btn_inje_re);

        table_inje.setModel(model1);
        jScrollPane3.setViewportView(table_inje);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("INJECTIONS", jPanel4);

        jScrollPane4.setViewportView(txt_dietadvice);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("DIET ADVICE", jPanel3);

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon.png"))); // NOI18N
        jButton1.setText("Enter Record");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator1);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Update-icon.png"))); // NOI18N
        jButton8.setText("Summary");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton8);
        jToolBar1.add(jSeparator2);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit-icon.png"))); // NOI18N
        jButton7.setText("Cancel");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);
        jToolBar1.add(jSeparator3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 95, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
if(txt_search.getText().equals("")){
    JOptionPane.showMessageDialog(null, "Please Enter the patient id");
    txt_search.setBackground(Color.GREEN);
    return;
}
        
        
        try {
//String report="D:\\NetbeansProject\\Hospital\\Reports\\report2.jrxml";
            JasperDesign jd = JRXmlLoader.load("Reports\\Patient_Summary.jrxml");
            String sql = "SELECT\n" +
"     patient.`PATIENT_ID` AS patient_PATIENT_ID,\n" +
"     patient.`TITLE` AS patient_TITLE,\n" +
"     patient.`FIRST_NAME` AS patient_FIRST_NAME,\n" +
"     patient.`LAST_NAME` AS patient_LAST_NAME,\n" +
"     patient.`GENDER` AS patient_GENDER,\n" +
"     patient.`EMAIL` AS patient_EMAIL,\n" +
"     patient.`MOBILE_NO` AS patient_MOBILE_NO,\n" +
"     patient_category.`MARITAL_STATUS` AS patient_category_MARITAL_STATUS,\n" +
"     patient_category.`BLOOD_GROUP` AS patient_category_BLOOD_GROUP,\n" +
"     patient_category.`TOWN` AS patient_category_TOWN,\n" +
"     patient_category.`AGE` AS patient_category_AGE,\n" +
"     patient_category.`VILLAGE` AS patient_category_VILLAGE\n" +
"FROM\n" +
"     `patient_category` patient_category INNER JOIN `patient` patient ON patient_category.`PATIENT_ID` = patient.`PATIENT_ID`\n" +
"WHERE\n" +
"      patient.`PATIENT_ID` =' "+pid+"'";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
            JasperViewer.viewReport(jp, false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
//clear();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Search();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        Search();        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        Search();        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        AddDrug adddr = new AddDrug(null, closable, this);
        adddr.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        Injection inj = new Injection(null, closable, this);
        inj.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void txt_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Insert();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_inje_reActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inje_reActionPerformed
  int r = table_inje.getSelectedRow();
   int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to remove the Injection?", "Remove Injection", JOptionPane.YES_NO_CANCEL_OPTION);
                if (p == JOptionPane.YES_OPTION) {
        model1.removeRow(r);   }     // TODO add your handling code here:
    }//GEN-LAST:event_btn_inje_reActionPerformed

    private void btn_r_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_r_mActionPerformed
  int r = table_med.getSelectedRow();
   int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to remove the Drug", "Remove Drug", JOptionPane.YES_NO_CANCEL_OPTION);
                if (p == JOptionPane.YES_OPTION) {
        model.removeRow(r);    }    // TODO add your handling code here:
    }//GEN-LAST:event_btn_r_mActionPerformed
    public void Insert() {
        if (txt_search.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the patient ID", "Alert", JOptionPane.ERROR_MESSAGE);
            txt_search.setBackground(Color.GREEN);

            return;
        }
        MedInsert();
        INJeInsert();
        DietInsert();
        JOptionPane.showMessageDialog(null, "Patient Prescriptions Details successfully Saved!!", "Alert", JOptionPane.INFORMATION_MESSAGE);
        txt_search.setText("");
        txt_dietadvice.setText("");
        this.setTitle("PRESCRIPTION");
SummaryDialog smd=new SummaryDialog(null, closable, pid);
smd.setVisible(true);
    }

    public void Search() {
        if (txt_search.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please enter the Patient ID");
            txt_search.setBackground(Color.GREEN);
            return;
        }
        String id = txt_search.getText();
        try {
            String sql1 = "SELECT patient.TITLE,patient.FIRST_NAME,patient.LAST_NAME,patient.PATIENT_ID from patient  WHERE patient.PATIENT_ID='" + id + "'";
            pst = con.prepareStatement(sql1);

            rs = pst.executeQuery();
            if (rs.next()) {
                pid = rs.getString("PATIENT_ID");

                titlee = rs.getString("TITLE");

                fname = rs.getString("FIRST_NAME");

                lname = rs.getString("LAST_NAME");

                txt_user.setText(titlee + " " + fname + " " + lname + " [" + pid + "]");
                this.setTitle(titlee + " " + fname + " " + lname + " [" + pid + "] " + " PRESCRIPTION");
            } else {
                JOptionPane.showMessageDialog(null, "Sorry!! The Patient ID does not exist", "Alert", JOptionPane.ERROR_MESSAGE);
                txt_search.setText("");
            }
        } catch (Exception e) {
        }
    }

    public void datenandtime() {
        Thread clock = new Thread() {
            public void run() {
                for (;;) {
                    Calendar cal = new GregorianCalendar();
                    month = cal.get(Calendar.MONTH);
                    year = cal.get(Calendar.YEAR);
                    day = cal.get(Calendar.DAY_OF_MONTH);
                    // date.setText(day + "/" + (month + 1) + "/" + year);

                    int second = cal.get(Calendar.SECOND);
                    int minute = cal.get(Calendar.MINUTE);
                    int hour = cal.get(Calendar.HOUR);

                    //   time.setText(hour + ":" + (minute) + ":" + second);
                    try {
                        sleep(1000);
                    } catch (InterruptedException ex) {
                    }
                }
            }
        };
        clock.start();
    }

    public void MedInsert() {

        xxx = table_med.getRowCount();

        if (xxx > 0) {

            for (int i = 0; i <= xxx - 1; i++) {
                try {

                    String mcode = table_med.getValueAt(i, 0).toString();
                    String mnme = table_med.getValueAt(i, 1).toString();
                    String dquantity = table_med.getValueAt(i, 2).toString();
                    String ditems = table_med.getValueAt(i, 3).toString();
                    String ddosage = table_med.getValueAt(i, 4).toString();
                    String dadmnin = table_med.getValueAt(i, 5).toString();
                    String dfreq = table_med.getValueAt(i, 6).toString();
                    String ddesc = table_med.getValueAt(i, 7).toString();
                    String dcost = table_med.getValueAt(i, 8).toString();
                    String sts = "pending";

                    String insertT = "insert into patient_medicine(PATIENT_ID,"
                            + "MEDICINE_CODE,DATE,MEDICINE_NAME,DRUG_QUANTITY,ITEMS,DOSAGE,ADMINISTRATION,FREQUENCY,MEDICINE_DESCRIPTION,STATUS) "
                            + "values('" + pid + "','" + mcode + "',"
                            + "'" + year + "/" + (month + 1) + "/" + day + "','" + mnme + "','" + dquantity + "','" + ditems + "','" + ddosage + "','" + dadmnin + "','" + dfreq + "','" + ddesc + "','" + sts + "')";

                    String insertm = "insert into patient_medicine_bill(PATIENT_ID,"
                            + "DATE,MEDICINE_NAME,M_COST) "
                            + "values('" + pid + "',"
                            + "'" + year + "/" + (month + 1) + "/" + day + "','" + mnme + "','" + dcost + "')";

                    Statement sttm = con.createStatement();
                    sttm.executeUpdate(insertT);
                    Statement stttm = con.createStatement();
                    stttm.executeUpdate(insertm);
   
                    String update_fee="Update patient_billing set medical_fee=(medical_fee+'"+dcost+"') where patient_billing.patient_id='" + pid + "'and date='" + year + "/" + (month + 1) + "/" + day + "'";
                      Statement stm = con.createStatement();
                        stm.executeUpdate(update_fee);
                    model.removeRow(xxx - 1);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex); //  Logger.getLogger(Consultation.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }

    }

    public void INJeInsert() {

        xxx2 = table_inje.getRowCount();
        if (xxx2 > 0) {

            for (int i = 0; i <= xxx2- 1; i++) {
                try {

                    String iname = table_inje.getValueAt(i, 0).toString();
                    String idesc = table_inje.getValueAt(i, 1).toString();
                    String idate = table_inje.getValueAt(i, 2).toString();
                    String sts = "pending";

                    String insertI = "insert into patient_injection(PATIENT_ID,"
                            + "NAME,DATE,DESCRIPTION,INJECTION_DATE,STATUS) "
                            + "values('" + pid + "','" + iname + "',"
                            + "'" + year + "/" + (month + 1) + "/" + day + "','" + idesc + "','" + idate + "','" + sts + "')";

                    Statement sttm = con.createStatement();

                    sttm.executeUpdate(insertI);
                    model1.removeRow(xxx2 - 1);

                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
//  Logger.getLogger(Consultation.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }

    public void DietInsert() {
        if (!txt_dietadvice.getText().equals("")) {

            try {
                String diet = txt_dietadvice.getText();
                String insertD = "insert into patient_diet_advice(PATIENT_ID,"
                        + "DATE,ADVICE) "
                        + "values('" + pid + "',"
                        + "'" + year + "/" + (month + 1)
                        + "/" + day + "','" + diet + "')";

                Statement sttm = con.createStatement();

                sttm.executeUpdate(insertD);
                

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
//  Logger.getLogger(Consultation.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_inje_re;
    private javax.swing.JButton btn_r_m;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    public javax.swing.JTable table_inje;
    public javax.swing.JTable table_med;
    private javax.swing.JTextPane txt_dietadvice;
    private javax.swing.JTextField txt_search;
    private javax.swing.JLabel txt_user;
    // End of variables declaration//GEN-END:variables
}
