/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital;

import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Dankiwan
 */
public class Receipt extends javax.swing.JInternalFrame {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form Receipt
     */
    public Receipt() {
        initComponents();
        con = javaconnect.ConnectDb();
        Receipttable();
        btn_print_receipt.setEnabled(false);

        ListSelectionModel listSelectionModel = receipt_table.getSelectionModel();
        listSelectionModel.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent lse) {
                ListSelectionModel lsm = (ListSelectionModel) lse.getSource();
                btn_print_receipt.setEnabled(!lsm.isSelectionEmpty());
            }
        });
    }

    public void Receipttable() {
        try {
            String s2 = "SELECT patient.patient_id as 'ID', patient.TITLE as 'Title'"
                    + ",patient.FIRST_NAME AS 'First Name', patient.LAST_NAME AS"
                    + " 'Last Name',payment.Receipt_No AS 'Receipt No',payment.Date AS 'Payment Date',payment.Amount AS 'Amount' from   payment INNER JOIN  patient ON payment.PATIENT_ID = patient.PATIENT_ID";

            pst = con.prepareStatement(s2);
            rs = pst.executeQuery();
            if (rs.next()) {
                receipt_table.setModel(DbUtils.resultSetToTableModel(rs));
            }
        } catch (SQLException ex) {
            //Logger.getLogger(LabTests.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void ReceipttableSearch() {
        try {
            String s2 = "SELECT patient.patient_id as 'ID', patient.TITLE as 'Title'"
                    + ",patient.FIRST_NAME AS 'First Name', patient.LAST_NAME AS"
                    + " 'Last Name',payment.Receipt_No AS 'Receipt No',payment.Date AS 'Payment Date',payment.Amount AS 'Amount' from   payment INNER JOIN  patient ON payment.PATIENT_ID = patient.PATIENT_ID where payment.PATIENT_ID='" + txt_pid.getText() + "'";

            pst = con.prepareStatement(s2);
            rs = pst.executeQuery();
            if (rs.next()) {
                receipt_table.setModel(DbUtils.resultSetToTableModel(rs));
            }
        } catch (SQLException ex) {
            //Logger.getLogger(LabTests.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btn_print_receipt = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        receipt_table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txt_pid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setTitle("RECEIPT");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btn_print_receipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer-icon.png"))); // NOI18N
        btn_print_receipt.setText("Print");
        btn_print_receipt.setFocusable(false);
        btn_print_receipt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_print_receipt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_print_receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_print_receiptActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_print_receipt);

        receipt_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(receipt_table);

        txt_pid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_pidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pidKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_pidKeyTyped(evt);
            }
        });

        jLabel1.setText("Enter the patient ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_pid, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_print_receiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_print_receiptActionPerformed
        Printreceipt();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_print_receiptActionPerformed

    private void txt_pidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pidKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pidKeyPressed

    private void txt_pidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pidKeyReleased
        ReceipttableSearch();        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pidKeyReleased

    private void txt_pidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pidKeyTyped
   char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pidKeyTyped

    public void Printreceipt() {
        int ro = receipt_table.getSelectedRow();
        String id = receipt_table.getValueAt(ro, 0).toString();
        try {
   String basePath = new File("src\\Reports\\Receipts.jrxml").getAbsolutePath();
    
            JasperDesign jd = JRXmlLoader.load(basePath);
            String sql = "SELECT\n"
                    + "     patient_billing.`CONSULTATION_FEE` AS patient_billing_CONSULTATION_FEE,\n"
                    + "     patient_billing.`MEDICAL_FEE` AS patient_billing_MEDICAL_FEE,\n"
                    + "     patient_billing.`LAB_FEE` AS patient_billing_LAB_FEE,\n"
                    + "     patient.`TITLE` AS patient_TITLE,\n"
                    + "     patient.`FIRST_NAME` AS patient_FIRST_NAME,\n"
                    + "     patient.`LAST_NAME` AS patient_LAST_NAME,\n"
                    + "     patient.`GENDER` AS patient_GENDER,\n"
                    + "     patient.`EMAIL` AS patient_EMAIL,\n"
                    + "     patient.`MOBILE_NO` AS patient_MOBILE_NO,\n"
                    + "     patient.`PATIENT_ID` AS patient_PATIENT_ID,\n"
                    + "     payment.`Receipt_No` AS payment_Receipt_No,\n"
                    + "     payment.`Amount` AS payment_Amount\n"
                    + "FROM\n"
                    + "     `patient_billing` patient_billing INNER JOIN `patient` patient ON patient_billing.`PATIENT_ID` = patient.`PATIENT_ID`\n"
                    + "     INNER JOIN `payment` payment ON patient.`PATIENT_ID` = payment.`PATIENT_ID`\n"
                    + "WHERE\n"
                    + "     patient.Patient_id = '" + id + "'";
            JRDesignQuery newQuery = new JRDesignQuery();
            newQuery.setText(sql);
            jd.setQuery(newQuery);
            JasperReport jr = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
            JasperViewer.viewReport(jp, false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_print_receipt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable receipt_table;
    private javax.swing.JTextField txt_pid;
    // End of variables declaration//GEN-END:variables
}
