/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hospital;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Dankiwan
 */
public class UserLog extends javax.swing.JInternalFrame {
 Connection con=null;
 ResultSet rs=null;
    PreparedStatement pst=null;
    /**
     * Creates new form UserLog
     */
    public UserLog() {
        initComponents();
        con=javaconnect.ConnectDb();
        jc_user_id.setSelectedIndex(0);
       
    }
private void log_table(){
   String  userid= (String) jc_user_id.getSelectedItem(); 
         
             if(jc_user_id.getSelectedIndex()==0){
                // String log="SELECT user.TITLE as Title,user.FIRST_NAME as First_name,user.LAST_NAME as Last_name,user_log.login_time as Login_Time,user_log.logout_time as Logout_Time,user_log.Time_Elapsed as Time_Elapsed FROM user,user_log WHERE (user.USER_ID=user_log.USER_ID) and user_log.Status='Logged out'";         
                 String log="SELECT user.TITLE as Title,user.FIRST_NAME as First_name,user.LAST_NAME as Last_name,user_log.login_time as Login_Time,user_log.logout_time as Logout_Time, Hour(logout_time-login_time) as Time_Elapsed FROM user,user_log WHERE (user.USER_ID=user_log.USER_ID) and user_log.Status='Logged out'";         
                
                 try {
                     pst=con.prepareStatement(log);
                 
            rs=pst.executeQuery(); 
                 if(rs.next()){
            userlog.setModel(DbUtils.resultSetToTableModel(rs));
        }
                 } catch (SQLException ex) {
                     Logger.getLogger(UserLog.class.getName()).log(Level.SEVERE, null, ex);
                 }
             }else{
       try {
           String log="SELECT user.TITLE as Title,user.FIRST_NAME as First_name,user.LAST_NAME as Last_name,user_log.login_time as Login_Time,user_log.logout_time as Logout_Time,user_log.Time_Elapsed as Time_Elapsed FROM user,user_log WHERE user.USER_ID='"+userid+"' and(user.USER_ID=user_log.USER_ID) and user_log.Status='Logged out'";
           
           pst=con.prepareStatement(log);
           rs=pst.executeQuery();
           if(rs.next()){
               userlog.setModel(DbUtils.resultSetToTableModel(rs));
           }
       } catch (SQLException ex) {
           Logger.getLogger(UserLog.class.getName()).log(Level.SEVERE, null, ex);
       }
}
     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userlog = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jc_user_id = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        jButton4 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton5 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton8 = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();

        setTitle("USER LOG");

        userlog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "First Name", "Last Name", "Login Time", "Logout Time", "Time Elapsed"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(userlog);

        jc_user_id.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "12", "14", "16", "18", "20" }));
        jc_user_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jc_user_idMouseClicked(evt);
            }
        });
        jc_user_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_user_idActionPerformed(evt);
            }
        });
        jc_user_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jc_user_idKeyReleased(evt);
            }
        });

        jLabel1.setText("User ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jc_user_id, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jc_user_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jToolBar2.setRollover(true);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/month-icon.png"))); // NOI18N
        jButton4.setText("This Month");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton4);
        jToolBar2.add(jSeparator4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/document-excel-icon.png"))); // NOI18N
        jButton5.setText("ALL");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton5);
        jToolBar2.add(jSeparator5);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer-icon.png"))); // NOI18N
        jButton8.setText("Print");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton8);
        jToolBar2.add(jSeparator7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jc_user_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_user_idActionPerformed
log_table();        // TODO add your handling code here:
    }//GEN-LAST:event_jc_user_idActionPerformed

    private void jc_user_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jc_user_idMouseClicked
log_table();        // TODO add your handling code here:
    }//GEN-LAST:event_jc_user_idMouseClicked

    private void jc_user_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jc_user_idKeyReleased
log_table();        // TODO add your handling code here:
    }//GEN-LAST:event_jc_user_idKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        /*  MessageFormat header=new MessageFormat("Mertmerg Hospital Records");
        MessageFormat footer=new MessageFormat("Page{0,number,integer}");
        try{
            info.print(JTable.PrintMode.NORMAL, header, footer);
        }
        catch(java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n",e.getMessage());
        }

        // TODO add your handling code here:*/
        //        printrepo();
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JComboBox jc_user_id;
    private javax.swing.JTable userlog;
    // End of variables declaration//GEN-END:variables
}
